services:
  postgres:
    image: postgres:14
    container_name: mlflow_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  mlflow:
    build: .
    container_name: mlflow_server
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - ./mlflow_artifacts:/artifacts

volumes:
  postgres_data: